apiVersion: apps/v1
kind: Deployment
metadata:
  name: creative-studio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: creative-studio
  template:
    metadata:
      labels:
        app: creative-studio
    spec:
      # imagePullSecrets:
      #   - name: harbor-secret
      containers:
        - name: creative-studio
          image: denisruparel28/creative-studio
          ports:
            - containerPort: 5000
#          envFrom:
#            - secretRef:
#                name: creative-studio-secrets
